import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-24 bg-void flex-row sticky w-screen gap-x-20 content-between opacity-100">
          {/*Logo*/}
          <div className="text-stark ml-8 mt-4 h-16 text-6xl col-span-2 w-4/12">
            Project
          </div>
          {/*Main redirects*/}
          <div className="flex justify-self-end text-stark mt-8 h-20 text-4xl -right-0 w-4/12">
            Passwords
          </div>
          {/*Login*/}
          <div className="flex justify-self-end text-stark pt-6 h-20 text-4xl -right-0 w-2/12 gap-x-12">
            <div className="pt-2">
              Login
            </div>
            <div className="rounded-full bg-jewel pl-4 pr-4 pt-2">
              Register
            </div>
          </div>
        </div>
        <div className="pt-24">
          {children}
        </div>
        <footer className="bg-void pb-5 bottom-0">
          <div className="max-w-screen-xl px-4 pt-8 mx-auto sm:px-6 lg:px-8">
            <div className="sm:flex sm:items-center sm:justify-between">
              <div className="flex justify-center text-teal-300 sm:justify-start">

              </div>
              <p className="mt-4 text-sm text-center text-stark lg:text-right lg:mt-0">
                T&C &nbsp; Career &nbsp; Privacy & Policy &nbsp; Developers
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
